### ISSUE TITLE
You have not supplied an API Access Key error

### ISSUE THREAD

**Issue by mickyjohnstonmonotype** [over-engineer/exchange-rates#6]
I am getting the following error when making the request `exchangeRates().latest().base(currencies.USD).fetch()`: **Cannot convert undefined or null to object**. Digging into this, the response coming back from the exchangerates.io service is: 

`{"success": false,"error": {"code": 101,"type": "missing_access_key","info": "You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]"}`

It seems exchangerates.io is now requiring an access key. Also, some other features - e.g. setting base currency to USD - is now limited to paid-only versions of the service. See https://github.com/exchangeratesapi/exchangeratesapi/issues/117 for more details.

**Comment by kwerty** [comment]
If the https://ratesapi.io/ and https://exchangerate.host/ APIs are able to provide the exact same response, perhaps @over-engineer might consider making a one line fix to switch to one of these?

**Comment by over-engineer** [comment]
Hey @mickyjohnstonmonotype, thanks for bringing this to my attention! It's unfortunate that exchangeratesapi.io (afaict) changed without any prior notice.

Likely, this wrapper works with pretty much any Fixer.io-compatible API. That means, switching to [ratesapi.io](https://ratesapi.io/) was a drop-in replacement, like @kwerty suggested.

I just pushed an update to npm, so it now uses ratesapi.io by default. 😄 

**You just have to update to the latest version (1.1.0) and everything will be back to normal. No breaking changes.**

---

I've also added a new `setApiBaseUrl()` function, which allows you to use a different API (any Fixer.io-compatible API will probably work).

See [Using a different API](https://github.com/over-engineer/exchange-rates#using-a-different-api).

For example, you can switch to [exchangerate.host](https://exchangerate.host/) like this:

```javascript
const { exchangeRates } = require('exchange-rates-api');

(async () => {
    await exchangeRates()
        .setApiBaseUrl('https://api.exchangerate.host')
        .latest()
        .fetch();    // {THB: 34.978, PHP: 58.159, …, HUF: 323.58}
})();
```

**Comment by kwerty** [comment]
The alternative API is now blocking CORS also.

Good thinking ahead @over-engineer ! Switched to another API with ease

await exchangeRates().setApiBaseUrl('https://api.exchangerate.host').
